1\. Let's flip a coin in Python
-------------------------------

00:00 - 00:36

Hi, I'm Alexander Ramirez, the CEO at Synergy Vision, which focuses on financial data science. This course is intended for people with basic knowledge about Python and familiarity with statistics. At the end of the course you'll have an understanding of basic probability concepts like random variables, calculations, probability distributions, and important results like the law of large numbers. We'll illustrate these concepts using simulations with Python.

2\. Probability
---------------

00:36 - 00:56

Probability is the foundation of many of the methods and models in data science. Statistical inference methods use data to understand the underlying processes behind the data. With probability, we can study the regularities that arise in random phenomena.

- Foundation of Data Science
- Allows to produce data from models
- Study regularities in random phenomena


3\. Gain intuition
------------------

00:56 - 01:14

Let's try to gain some intuition about probability by starting with the classic random experiment, a coin flip. We'll start simulating with Python and learn to calculate probabilities and work with probability distributions.

```markdown
...with coin flips
          O
       ___|______
      |         |
      |         |
      |  \_____/|   
      |    |     |    <- Coin
      |   /      |
      |  |       |
      |  |       |
       \ |_______/
        |       
  ______|______
 /      |      \
|  Hand |       |
|_______|_______|   <- Hand tossing coin
```

4\. Only two outcomes
---------------------

01:14 - 02:08

If you flip a coin there are two possible outcomes: heads or tails. This random experiment is called a Bernoulli trial, after Jacob Bernoulli. A Bernoulli trial is one where the possible outcomes are binary: they can be modeled as success or failure, yes or no, or on or off. In this case the experiment is the flip of a coin; the possible outcomes are success (getting heads) or failure (getting tails). Each outcome is called an event. You assign probabilities to events. With a fair coin you have a 50% chance of getting heads and a 50% chance of getting tails for each event.

```markdown
Heads or Tails:
     _______
    /       \
   |   IN    |
   |  GOD WE |
   |  TRUST  |   <- Heads (Lincoln's side)
   |         |
   | LIBERTY |
    \_______/
    
         |   
         | (flip)
         |
    _______
   /       \
  | UNITED  |
  | STATES  |   <- Tails (Lincoln Memorial side)
  | OF      |
  | AMERICA |
  | ONE CENT|
   \_______/
```

5\. Flipping a coin in Python
-----------------------------

02:08 - 02:53

To simulate the coin flips, we will use the bernoulli object from the Python library scipy dot stats. We can call bernoulli dot rvs, specifying two arguments, to generate random variates. The first argument is p, the probability of success, which in this case is 0.5; the second is size, which is the number of coin flips, in this case 1. The result of the first call was 0, or tails. After executing the call a second time we got 1, or heads.

```python
from scipy.stats import bernoulli

# Bernoulli random experiment
bernoulli.rvs(p=0.5, size=1)
```
```plaintext
array([0])
```

```python
# Another draw
bernoulli.rvs(p=0.5, size=1)
```
```plaintext
array([1])
```

6\. Flipping multiple coins
---------------------------

02:53 - 03:08

For 10 coin flips, size equals 10. We can use sum to know how many heads we got. The first time, we got 5 heads and 5 tails.

```python
# Change size parameter to flip more...
bernoulli.rvs(p=0.5, size=10)
```
```plaintext
array([0, 0, 0, 0, 0, 0, 1, 1, 0, 0])
```

```python
# How many heads?
sum(bernoulli.rvs(p=0.5, size=10))
```
```plaintext
5
```

7\. Flipping multiple coins (Cont.)
-----------------------------------

03:08 - 03:13

After another draw, we got 2 heads and 8 tails. So, we can appreciate the randomness.

```python
# Another draw...
sum(bernoulli.rvs(p=0.5, size=10))
```
```plaintext
2
```

8\. Flipping multiple coins (Cont.)
-----------------------------------

03:13 - 03:59

A sequence of independent Bernoulli trials follows the binomial distribution. So, instead of using the bernoulli object and adding the outcomes, we can use the binomial distribution and the binom object. We'll use three arguments: n for the number of coin flips, p for the probability of success, and size for the number of draws of the same experiment. On the first execution we got 7 heads out of 10 flips. Let's try 10 more times. As we can see, 5 is the result that repeats most often for a fair coin.

```python
from scipy.stats import binom

# Binomial random variable
binom.rvs(n=10, p=0.5, size=1)
```
```plaintext
array([7])
```

```python
# Many draws
binom.rvs(n=10, p=0.5, size=10)
```
```plaintext
array([6, 2, 3, 5, 5, 5, 5, 4, 6, 6])
```

9\. Flipping multiple coins (Cont.)
-----------------------------------

03:59 - 04:15

We can also change the probability of getting heads to 0.3, and see how that affects the results. As you may notice already, we can observe different outcomes using biased coins.

```python
# Biased coin draws
binom.rvs(n=10, p=0.3, size=10)
```
```plaintext
array([3, 4, 3, 3, 2, 2, 2, 2, 3, 6])
```

10\. Random generator seed
--------------------------

04:15 - 04:54

We use random number generators to simulate the outcome of random experiment. If you run the same command with the same random seed, you will always get the same result. In Python we need to set a seed for the generator to produce similar outcomes in each experiment. Then we can check if the results are what we expected. We have two options to configure the generator: using the random_state parameter of the rvs function or using numpy dot random dot seed.

```python
# Use the random_state parameter of the rvs() function
from scipy.stats import binom
binom.rvs(n=10, p=0.5, size=1, random_state=42)
```

```python
# Use numpy.random.seed()
import numpy as np
np.random.seed(42)
```

11\. Random generator seed (Cont.)
----------------------------------

04:54 - 05:00

For convenience, we will mostly use the numpy method throughout this course.

```python
from scipy.stats import binom
import numpy as np

np.random.seed(42)
binom.rvs(n=10, p=0.5, size=1)
```

```python
array([4])
```

12\. Let's practice flipping coins in Python
--------------------------------------------

05:00 - 05:12

We can do some more experiments like this to get a sense about the outcomes that are most likely. So, let's practice flipping coins in Python!

Flipping coins
==============

This exercise requires the `bernoulli` object from the `scipy.stats` library to simulate the two possible outcomes from a coin flip, `1`("heads") or `0` ("tails"), and the `numpy` library (loaded as `np`) to set the random generator seed.

You'll use the `bernoulli.rvs()` function to simulate coin flips using the `size` argument. 

You will set the random seed so you can reproduce the results for the random experiment in each exercise.

From each experiment, you will get the values of each coin flip. You can add the coin flips to get the number of heads after flipping 10 coins using the `sum()` function.

Instructions 1/3
----------------

-   Import `bernoulli` from `scipy.stats`, set the seed with `np.random.seed()`. Simulate 1 flip, with a 35% chance of heads.

In [ ]:
# Import the bernoulli object from scipy.stats
from scipy.stats import bernoulli

# Set the random seed to reproduce the results
np.random.seed(42)

# Simulate one coin flip with 35% chance of getting heads
coin_flip = bernoulli.rvs(p=.35, size=1)
print(coin_flip)

Instructions 2/3
----------------

-   Use `bernoulli.rvs()` and `sum()` to get the number of heads after 10 coin flips with 35% chance of getting heads.

In [ ]:
# Import the bernoulli object from scipy.stats
from scipy.stats import bernoulli

# Set the random seed to reproduce the results
np.random.seed(42)

# Simulate ten coin flips and get the number of heads
ten_coin_flips = bernoulli.rvs(p=.35, size=10)
coin_flips_sum = sum(ten_coin_flips)
print(coin_flips_sum)

Instructions 3/3
----------------

-   Using `bernoulli.rvs()` and `sum()`, try to get the number of heads after 5 flips with a 50% chance of getting heads.

In [ ]:
# Import the bernoulli object from scipy.stats
from scipy.stats import bernoulli

# Set the random seed to reproduce the results
np.random.seed(42)

# Simulate ten coin flips and get the number of heads
five_coin_flips = bernoulli.rvs(p=0.5, size=5)
coin_flips_sum = sum(five_coin_flips)
print(coin_flips_sum)

Using binom to flip even more coins
===================================

Previously, you simulated 10 coin flips with a 35% chance of getting heads using `bernoulli.rvs()`.

This exercise loads the `binom` object from `scipy.stats` so you can use `binom.rvs()` to simulate 20 trials of 10 coin flips with a 35% chance of getting heads on each coin flip.

Instructions
------------

-   Use the `binom.rvs()` function to simulate 20 trials of 10 coin flips with a 35% chance of getting heads.

In [ ]:
# Set the random seed to reproduce the results
np.random.seed(42)

# Simulate 20 trials of 10 coin flips 
draws = binom.rvs(n=10, p=.35, size=20)
print(draws)

1\. Probability mass and distribution functions
-----------------------------------------------

00:00 - 00:22

After conducting many random experiments, you will notice that some outcomes are more likely than others. This is called a probability distribution. There are two important functions that are useful for probability calculations: the probability mass function and the cumulative distribution function.


2\. Probability mass function (pmf)
-----------------------------------

00:22 - 00:49

A discrete random variable has a finite number of possible outcomes. The probability mass function allows you to calculate the probability of getting a particular outcome for a discrete random variable. The binomial probability mass function allows you to calculate the probability of getting k heads from n coin flips with p probability of getting heads.

$binomial.pmf(k, n, p) = \binom{n}{k} p^k (1 - p)^{n - k}$

3\. Probability mass function (pmf)
-----------------------------------

00:49 - 00:54

The formula multiplies the number of different ways that you can get k successes out of n coin flips...

$binomial.pmf(k, n, p) = \color{red}{\binom{n}{k}} p^k (1 - p)^{n - k}$

4\. Probability mass function (pmf) (Cont.)
-------------------------------------------

00:54 - 00:59

by the probability of success raised to the number of successes, k...

$binomial.pmf(k, n, p) = \binom{n}{k} \color{red}{p^k} (1 - p)^{n - k}$

5\. Probability mass function (pmf) (Cont.)
-------------------------------------------

00:59 - 01:13

by the probability of failure, 1 - p, raised to the number of failures, n - k. It's okay if you don't understand the formula right now. With practice, your intuition about this will grow.

$binomial.pmf(k, n, p) = \binom{n}{k} p^k \color{red}{(1 - p)^{n - k}}$

6\. Probability mass function (pmf)
-----------------------------------

01:13 - 01:25

If we plot the probability mass function of getting k heads out of 10 fair coin flips, you can see that 5 is the most likely outcome.

### Binomial Distribution PMF

**binom.pmf(k=5, n=10, p=0.5) = 24.6%**

| k  | P(X = k) |
|----|----------|
| 0  | 0.001    |
| 1  | 0.010    |
| 2  | 0.044    |
| 3  | 0.117    |
| 4  | 0.205    |
| 5  | **0.246** |
| 6  | 0.205    |
| 7  | 0.117    |
| 8  | 0.044    |
| 9  | 0.010    |
| 10 | 0.001    |

The binomial probability mass function (PMF) is:

$$
P(X = k) = \binom{n}{k} p^k (1 - p)^{n-k}
$$

For \( n = 10 \), \( p = 0.5 \), the most likely outcome is \( k = 5 \), with probability:

$$
P(X = 5) = \binom{10}{5} (0.5)^5 (1 - 0.5)^{5} = 0.246
$$

7\. Probability mass function (pmf) (Cont.)
-------------------------------------------

01:25 - 01:33

With the scipy dot stats library we can use the binom dot pmf function to calculate this probability.

$binomial.pmf(k, n, p) = \binom{n}{k} p^k (1 - p)^{n - k}$

**In Python:**

```python
binom.pmf(k, n, p)
```

```

8\. Calculating probabilities with `binom.pmf()`
------------------------------------------------

01:33 - 01:59

If you use binom dot pmf with parameters k equals 2, n equals 10, and p equals 0.5 you get the probability of getting 2 heads from 10 flips of a fair coin -- that is, 4%. The probability of getting 5 heads from 10 coin flips is almost 25%.

```python
# Probability of 2 heads after 10 throws with a fair coin
binom.pmf(k=2, n=10, p=0.5)
```

```python
0.04394531249999999
```

```python
# Probability of 5 heads after 10 throws with a fair coin
binom.pmf(k=5, n=10, p=0.5)
```

```python
0.24609375000000003
```

9\. Calculating probabilities with binom.pmf() (Cont.)
------------------------------------------------------

01:59 - 02:34

The probability of getting 50 heads out of 100 flips of a biased coin with 30% probability of getting heads is extremely small: not even a 1% chance. If instead you calculate the probability of getting 65 heads from 100 flips of a biased coin with 70% probability of getting heads, you see that it's almost 5%. As n gets larger, the probability of getting k heads becomes smaller for the same p.

```python
# Probability of 50 heads after 100 throws with p=0.3
binom.pmf(k=50, n=100, p=0.3)
```

```python
1.3026227131445298e-05
```

```python
# Probability of 65 heads after 100 throws with p=0.7
binom.pmf(k=65, n=100, p=0.7)
```

```python
0.0467796823527298
```